### ISSUE TITLE
Print current/next version & dry-run

### ISSUE THREAD

**Issue by flyte** [inirudebwoy/bamp#17]
Add a flag to print the current/next version so it can be used in scripts etc.

For example:

```bash
$ # Print current version
$ bamp --print
1.2.3
$ bamp patch --print --dry-run
1.2.4
$ bamp minor --print --dry-run
1.3.0
$ bamp major --print --dry-run
2.0.0
$ bamp --print -n
1.2.3$ # This should not print a \n at the end
```

Some possible names for the flag:
- `--output[-version]`
- `--print[-version]`
- `--show[-version]`

It should output `1.2.3\n` but it'd be helpful to add an `-n` to not output the newline (same as `echo`) in order to incorporate it into a script, such as

``` bash
git flow release start $(bamp patch -n --print --dry-run)
```

**Comment by inirudebwoy** [comment]
Thanks for the idea, I like it. This is something that would really be useful when you want to use bamp in CI or some release scripts you may have.
👍

**Comment by flyte** [comment]
An alternative implementation might be to make sure that all human-readable output is done to stderr and only the version number is output on stdout. That would mean that the default output would simply be `1.2.3\n` and you can use `-n` to remove the newline. This is similar to tools such as curl, where the progress and other information is displayed on stderr and only the content is sent over stdout.

**Comment by inirudebwoy** [comment]
Solved. Thanks for your input and feedback :)
